const POSTGRESQL_ACCOUNT_OBJECTS: &[ColumnDescriptor] = &[
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_pkey",kind:"p|true|false|false|{1}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|PRIMARY KEY (id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_user_id_fkey",kind:"f|true|false|false|{2}|Some(\"{1}\")|Some(\"a\")|Some(\"c\")|Some(\"s\")|Some(\"public\")|Some(\"users\")|FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_user_id_id_key",kind:"u|true|false|false|{2,1}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (user_id, id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_apple_id_key",kind:"u|true|false|false|{23}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (apple_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_custom_id_key",kind:"u|true|false|false|{16}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (custom_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_edge_count_check",kind:"c|true|false|false|{17}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|CHECK ((edge_count >= 0))",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_email_key",kind:"u|true|false|false|{10}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (email)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_facebook_id_key",kind:"u|true|false|false|{12}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (facebook_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_facebook_instant_game_id_key",kind:"u|true|false|false|{22}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (facebook_instant_game_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_gamecenter_id_key",kind:"u|true|false|false|{14}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (gamecenter_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_google_id_key",kind:"u|true|false|false|{13}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (google_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_password_check",kind:"c|true|false|false|{11}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|CHECK ((length(password) < 32000))",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_pkey",kind:"p|true|false|false|{1}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|PRIMARY KEY (id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_steam_id_key",kind:"u|true|false|false|{15}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (steam_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_username_key",kind:"u|true|false|false|{2}|None|Some(\" \")|Some(\" \")|Some(\" \")|None|None|UNIQUE (username)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@index:user_device_pkey",kind:"true|true|true|true|1|None|CREATE UNIQUE INDEX user_device_pkey ON public.user_device USING btree (id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@index:user_device_user_id_id_key",kind:"true|false|true|true|2 1|None|CREATE UNIQUE INDEX user_device_user_id_id_key ON public.user_device USING btree (user_id, id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_apple_id_key",kind:"true|false|true|true|23|None|CREATE UNIQUE INDEX users_apple_id_key ON public.users USING btree (apple_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_custom_id_key",kind:"true|false|true|true|16|None|CREATE UNIQUE INDEX users_custom_id_key ON public.users USING btree (custom_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_email_key",kind:"true|false|true|true|10|None|CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_facebook_id_key",kind:"true|false|true|true|12|None|CREATE UNIQUE INDEX users_facebook_id_key ON public.users USING btree (facebook_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_facebook_instant_game_id_key",kind:"true|false|true|true|22|None|CREATE UNIQUE INDEX users_facebook_instant_game_id_key ON public.users USING btree (facebook_instant_game_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_gamecenter_id_key",kind:"true|false|true|true|14|None|CREATE UNIQUE INDEX users_gamecenter_id_key ON public.users USING btree (gamecenter_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_google_id_key",kind:"true|false|true|true|13|None|CREATE UNIQUE INDEX users_google_id_key ON public.users USING btree (google_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_pkey",kind:"true|true|true|true|1|None|CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_steam_id_key",kind:"true|false|true|true|15|None|CREATE UNIQUE INDEX users_steam_id_key ON public.users USING btree (steam_id)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_username_key",kind:"true|false|true|true|2|None|CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@table",kind:"BASE TABLE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@table",kind:"BASE TABLE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@fk-triggers",kind:"postgresql-native-four-fk-triggers",nullable:false,default_zero:false,character_maximum_length:None},
];
const COCKROACHDB_ACCOUNT_OBJECTS: &[ColumnDescriptor] = &[
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_pkey",kind:"p|true|false|false|{1}|None|None|None|None|None|None|PRIMARY KEY (id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_user_id_fkey",kind:"f|true|false|false|{2}|Some(\"{1}\")|Some(\"a\")|Some(\"c\")|Some(\"s\")|Some(\"public\")|Some(\"users\")|FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@constraint:user_device_user_id_id_key",kind:"u|true|false|false|{2,1}|None|None|None|None|None|None|UNIQUE (user_id ASC, id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_apple_id_key",kind:"u|true|false|false|{23}|None|None|None|None|None|None|UNIQUE (apple_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_custom_id_key",kind:"u|true|false|false|{16}|None|None|None|None|None|None|UNIQUE (custom_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_edge_count_check",kind:"c|true|false|false|{17}|None|None|None|None|None|None|CHECK ((edge_count >= 0))",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_email_key",kind:"u|true|false|false|{10}|None|None|None|None|None|None|UNIQUE (email ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_facebook_id_key",kind:"u|true|false|false|{12}|None|None|None|None|None|None|UNIQUE (facebook_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_facebook_instant_game_id_key",kind:"u|true|false|false|{22}|None|None|None|None|None|None|UNIQUE (facebook_instant_game_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_gamecenter_id_key",kind:"u|true|false|false|{14}|None|None|None|None|None|None|UNIQUE (gamecenter_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_google_id_key",kind:"u|true|false|false|{13}|None|None|None|None|None|None|UNIQUE (google_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_password_check",kind:"c|true|false|false|{11}|None|None|None|None|None|None|CHECK ((length(password) < 32000))",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_pkey",kind:"p|true|false|false|{1}|None|None|None|None|None|None|PRIMARY KEY (id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_steam_id_key",kind:"u|true|false|false|{15}|None|None|None|None|None|None|UNIQUE (steam_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@constraint:users_username_key",kind:"u|true|false|false|{2}|None|None|None|None|None|None|UNIQUE (username ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@index:user_device_pkey",kind:"true|true|true|false|1|None|CREATE UNIQUE INDEX user_device_pkey ON {database}.public.user_device USING btree (id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@index:user_device_user_id_id_key",kind:"true|false|true|false|2 1|None|CREATE UNIQUE INDEX user_device_user_id_id_key ON {database}.public.user_device USING btree (user_id ASC, id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_apple_id_key",kind:"true|false|true|false|23|None|CREATE UNIQUE INDEX users_apple_id_key ON {database}.public.users USING btree (apple_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_custom_id_key",kind:"true|false|true|false|16|None|CREATE UNIQUE INDEX users_custom_id_key ON {database}.public.users USING btree (custom_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_email_key",kind:"true|false|true|false|10|None|CREATE UNIQUE INDEX users_email_key ON {database}.public.users USING btree (email ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_facebook_id_key",kind:"true|false|true|false|12|None|CREATE UNIQUE INDEX users_facebook_id_key ON {database}.public.users USING btree (facebook_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_facebook_instant_game_id_key",kind:"true|false|true|false|22|None|CREATE UNIQUE INDEX users_facebook_instant_game_id_key ON {database}.public.users USING btree (facebook_instant_game_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_gamecenter_id_key",kind:"true|false|true|false|14|None|CREATE UNIQUE INDEX users_gamecenter_id_key ON {database}.public.users USING btree (gamecenter_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_google_id_key",kind:"true|false|true|false|13|None|CREATE UNIQUE INDEX users_google_id_key ON {database}.public.users USING btree (google_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_pkey",kind:"true|true|true|false|1|None|CREATE UNIQUE INDEX users_pkey ON {database}.public.users USING btree (id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_steam_id_key",kind:"true|false|true|false|15|None|CREATE UNIQUE INDEX users_steam_id_key ON {database}.public.users USING btree (steam_id ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@index:users_username_key",kind:"true|false|true|false|2|None|CREATE UNIQUE INDEX users_username_key ON {database}.public.users USING btree (username ASC)",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"users",name:"@table",kind:"BASE TABLE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@table",kind:"BASE TABLE",nullable:false,default_zero:false,character_maximum_length:None},
ColumnDescriptor {table:"user_device",name:"@fk-triggers",kind:"cockroachdb-native-no-pg-trigger-rows",nullable:false,default_zero:false,character_maximum_length:None},
];
fn account_catalog_objects(
    profile: DatabaseProfile,
    table: &str,
) -> impl Iterator<Item = ColumnDescriptor> + '_ {
    let all = match profile {
        DatabaseProfile::PostgreSql => POSTGRESQL_ACCOUNT_OBJECTS,
        DatabaseProfile::CockroachDb => COCKROACHDB_ACCOUNT_OBJECTS,
    };
    all.iter().copied().filter(move |x| x.table == table)
}
