// Exact pg_attribute/pg_type/pg_collation observations from owned pinned profiles.
// No domain/generated/identity/type precision/collation drift can be projected away.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct AccountNativeAttribute<'a> {
    table_name: &'a str,
    column_name: &'a str,
    attnum: i64,
    native_type_oid: u32,
    atttypmod: i64,
    attnotnull: bool,
    generated: &'a str,
    identity: &'a str,
    collation_oid: u32,
    type_namespace: &'a str,
    typname: &'a str,
    type_kind: &'a str,
    domain_base_oid: u32,
    collation_namespace: Option<&'a str>,
    collation_name: Option<&'a str>,
}
const POSTGRESQL_ACCOUNT_NATIVE_ATTRIBUTES: &[AccountNativeAttribute<'static>] = &[
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "id",
        attnum: 1,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "user_id",
        attnum: 2,
        native_type_oid: 2950,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "uuid",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "preferences",
        attnum: 3,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_amazon",
        attnum: 4,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_android",
        attnum: 5,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_huawei",
        attnum: 6,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_ios",
        attnum: 7,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_web",
        attnum: 8,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "id",
        attnum: 1,
        native_type_oid: 2950,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "uuid",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "username",
        attnum: 2,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "display_name",
        attnum: 3,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "avatar_url",
        attnum: 4,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "lang_tag",
        attnum: 5,
        native_type_oid: 1043,
        atttypmod: 22,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "location",
        attnum: 6,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "timezone",
        attnum: 7,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "metadata",
        attnum: 8,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "wallet",
        attnum: 9,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "email",
        attnum: 10,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "password",
        attnum: 11,
        native_type_oid: 17,
        atttypmod: -1,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "bytea",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "facebook_id",
        attnum: 12,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "google_id",
        attnum: 13,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "gamecenter_id",
        attnum: 14,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "steam_id",
        attnum: 15,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "custom_id",
        attnum: 16,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "edge_count",
        attnum: 17,
        native_type_oid: 23,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "int4",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "create_time",
        attnum: 18,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "update_time",
        attnum: 19,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "verify_time",
        attnum: 20,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "disable_time",
        attnum: 21,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "facebook_instant_game_id",
        attnum: 22,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "apple_id",
        attnum: 23,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 100,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
];
const COCKROACHDB_ACCOUNT_NATIVE_ATTRIBUTES: &[AccountNativeAttribute<'static>] = &[
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "id",
        attnum: 1,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "user_id",
        attnum: 2,
        native_type_oid: 2950,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "uuid",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "preferences",
        attnum: 3,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_amazon",
        attnum: 4,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_android",
        attnum: 5,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_huawei",
        attnum: 6,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_ios",
        attnum: 7,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "user_device",
        column_name: "push_token_web",
        attnum: 8,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "id",
        attnum: 1,
        native_type_oid: 2950,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "uuid",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "username",
        attnum: 2,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "display_name",
        attnum: 3,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "avatar_url",
        attnum: 4,
        native_type_oid: 1043,
        atttypmod: 516,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "lang_tag",
        attnum: 5,
        native_type_oid: 1043,
        atttypmod: 22,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "location",
        attnum: 6,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "timezone",
        attnum: 7,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "metadata",
        attnum: 8,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "wallet",
        attnum: 9,
        native_type_oid: 3802,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "jsonb",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "email",
        attnum: 10,
        native_type_oid: 1043,
        atttypmod: 259,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "password",
        attnum: 11,
        native_type_oid: 17,
        atttypmod: -1,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "bytea",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "facebook_id",
        attnum: 12,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "google_id",
        attnum: 13,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "gamecenter_id",
        attnum: 14,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "steam_id",
        attnum: 15,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "custom_id",
        attnum: 16,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "edge_count",
        attnum: 17,
        native_type_oid: 20,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "int8",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "create_time",
        attnum: 18,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "update_time",
        attnum: 19,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "verify_time",
        attnum: 20,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "disable_time",
        attnum: 21,
        native_type_oid: 1184,
        atttypmod: -1,
        attnotnull: true,
        generated: "",
        identity: "",
        collation_oid: 0,
        type_namespace: "pg_catalog",
        typname: "timestamptz",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: None,
        collation_name: None,
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "facebook_instant_game_id",
        attnum: 22,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
    AccountNativeAttribute {
        table_name: "users",
        column_name: "apple_id",
        attnum: 23,
        native_type_oid: 1043,
        atttypmod: 132,
        attnotnull: false,
        generated: "",
        identity: "",
        collation_oid: 3403232968,
        type_namespace: "pg_catalog",
        typname: "varchar",
        type_kind: "b",
        domain_base_oid: 0,
        collation_namespace: Some("pg_catalog"),
        collation_name: Some("default"),
    },
];

fn native_account_attribute_bindings(
    profile: DatabaseProfile,
) -> &'static [AccountNativeAttribute<'static>] {
    match profile {
        DatabaseProfile::PostgreSql => POSTGRESQL_ACCOUNT_NATIVE_ATTRIBUTES,
        DatabaseProfile::CockroachDb => COCKROACHDB_ACCOUNT_NATIVE_ATTRIBUTES,
    }
}
fn matches_native_account_attribute(
    profile: DatabaseProfile,
    actual: AccountNativeAttribute<'_>,
) -> bool {
    native_account_attribute_bindings(profile).contains(&actual)
}
fn require_account_native_attribute_binding(
    client: &mut impl GenericClient,
    catalog: &Catalog,
) -> Result<DatabaseProfile, DomainError> {
    let profile: String = client.query_one("SELECT CASE WHEN version() LIKE 'PostgreSQL %' THEN 'postgresql' WHEN version() LIKE 'CockroachDB %' THEN 'cockroachdb' ELSE 'unknown' END", &[]).map_err(map_postgres_error)?.try_get(0).map_err(map_postgres_error)?;
    let profile = match profile.as_str() {
        "postgresql" => DatabaseProfile::PostgreSql,
        "cockroachdb" => DatabaseProfile::CockroachDb,
        _ => {
            return Err(failed_precondition(
                "schema5_account_native_profile_unknown",
            ))
        }
    };
    let rows = client.query("SELECT CASE WHEN octet_length(c.relname) <= 128 THEN c.relname ELSE NULL END,CASE WHEN octet_length(a.attname) <= 128 THEN a.attname ELSE NULL END,a.attnum::BIGINT,a.atttypid,a.atttypmod::BIGINT,a.attnotnull,a.attgenerated::TEXT,a.attidentity::TEXT,a.attcollation,CASE WHEN octet_length(tn.nspname) <= 128 THEN tn.nspname ELSE NULL END,CASE WHEN octet_length(t.typname) <= 128 THEN t.typname ELSE NULL END,t.typtype::TEXT,t.typbasetype,CASE WHEN octet_length(cn.nspname) <= 128 THEN cn.nspname ELSE NULL END,CASE WHEN octet_length(co.collname) <= 128 THEN co.collname ELSE NULL END, (COALESCE(octet_length(c.relname) > 128,false) OR COALESCE(octet_length(a.attname) > 128,false) OR COALESCE(octet_length(tn.nspname) > 128,false) OR COALESCE(octet_length(t.typname) > 128,false) OR COALESCE(octet_length(cn.nspname) > 128,false) OR COALESCE(octet_length(co.collname) > 128,false)) FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_type t ON t.oid=a.atttypid JOIN pg_catalog.pg_namespace tn ON tn.oid=t.typnamespace LEFT JOIN pg_catalog.pg_collation co ON co.oid=a.attcollation LEFT JOIN pg_catalog.pg_namespace cn ON cn.oid=co.collnamespace WHERE n.nspname='public' AND c.relname IN ('users','user_device') AND a.attnum>0 AND NOT a.attisdropped ORDER BY c.relname,a.attnum LIMIT 33", &[]).map_err(map_postgres_error)?;
    let expected = catalog
        .keys()
        .filter(|(table, name)| {
            matches!(table.as_str(), "users" | "user_device") && !name.starts_with('@')
        })
        .count();
    if rows.len() > 32 || rows.len() != expected {
        return Err(failed_precondition(
            "schema5_account_native_attribute_inventory",
        ));
    }
    let mut seen = std::collections::BTreeSet::new();
    for row in rows {
        if row.try_get::<_, bool>(15).map_err(map_postgres_error)? {
            return Err(failed_precondition(
                "schema5_account_native_attribute_wire_budget",
            ));
        }
        let table: String = row.try_get(0).map_err(map_postgres_error)?;
        let name: String = row.try_get(1).map_err(map_postgres_error)?;
        let generated: String = row.try_get(6).map_err(map_postgres_error)?;
        let identity: String = row.try_get(7).map_err(map_postgres_error)?;
        let namespace: String = row.try_get(9).map_err(map_postgres_error)?;
        let type_name: String = row.try_get(10).map_err(map_postgres_error)?;
        let kind: String = row.try_get(11).map_err(map_postgres_error)?;
        let collation_namespace: Option<String> = row.try_get(13).map_err(map_postgres_error)?;
        let collation_name: Option<String> = row.try_get(14).map_err(map_postgres_error)?;
        let actual = AccountNativeAttribute {
            table_name: &table,
            column_name: &name,
            attnum: row.try_get(2).map_err(map_postgres_error)?,
            native_type_oid: row.try_get(3).map_err(map_postgres_error)?,
            atttypmod: row.try_get(4).map_err(map_postgres_error)?,
            attnotnull: row.try_get(5).map_err(map_postgres_error)?,
            generated: &generated,
            identity: &identity,
            collation_oid: row.try_get(8).map_err(map_postgres_error)?,
            type_namespace: &namespace,
            typname: &type_name,
            type_kind: &kind,
            domain_base_oid: row.try_get(12).map_err(map_postgres_error)?,
            collation_namespace: collation_namespace.as_deref(),
            collation_name: collation_name.as_deref(),
        };
        if !matches_native_account_attribute(profile, actual) || !seen.insert((table, name)) {
            return Err(failed_precondition(
                "schema5_account_native_attribute_drift",
            ));
        }
    }
    Ok(profile)
}
#[cfg(test)]
mod account_native_attribute_tests {
    use super::*;
    #[test]
    fn both_captured_profiles_match_all_31_native_attributes() {
        for profile in [DatabaseProfile::PostgreSql, DatabaseProfile::CockroachDb] {
            let rows = native_account_attribute_bindings(profile);
            assert_eq!(rows.len(), 31);
            for &row in rows {
                assert!(matches_native_account_attribute(profile, row));
            }
        }
    }
    #[test]
    fn domain_generated_identity_precision_and_collation_cannot_hide_in_projection() {
        for profile in [DatabaseProfile::PostgreSql, DatabaseProfile::CockroachDb] {
            for &row in native_account_attribute_bindings(profile) {
                let mutations = [
                    AccountNativeAttribute {
                        native_type_oid: 999999,
                        ..row
                    },
                    AccountNativeAttribute {
                        domain_base_oid: row.native_type_oid,
                        type_kind: "d",
                        ..row
                    },
                    AccountNativeAttribute {
                        generated: "s",
                        ..row
                    },
                    AccountNativeAttribute {
                        identity: "a",
                        ..row
                    },
                    AccountNativeAttribute {
                        atttypmod: row.atttypmod + 1,
                        ..row
                    },
                    AccountNativeAttribute {
                        attnum: row.attnum + 1,
                        ..row
                    },
                    AccountNativeAttribute {
                        attnotnull: !row.attnotnull,
                        ..row
                    },
                    AccountNativeAttribute {
                        type_namespace: "public",
                        ..row
                    },
                    AccountNativeAttribute {
                        typname: "user_domain",
                        ..row
                    },
                    AccountNativeAttribute {
                        collation_oid: row.collation_oid + 1,
                        ..row
                    },
                    AccountNativeAttribute {
                        collation_namespace: Some("public"),
                        ..row
                    },
                    AccountNativeAttribute {
                        collation_name: Some("unexpected"),
                        ..row
                    },
                    AccountNativeAttribute {
                        column_name: "unexpected",
                        ..row
                    },
                    AccountNativeAttribute {
                        table_name: "unexpected",
                        ..row
                    },
                ];
                for changed in mutations {
                    assert!(!matches_native_account_attribute(profile, changed));
                }
            }
        }
    }
    #[test]
    fn pg_and_cr_native_integer_and_default_collation_are_distinct() {
        for (from, to) in [
            (DatabaseProfile::PostgreSql, DatabaseProfile::CockroachDb),
            (DatabaseProfile::CockroachDb, DatabaseProfile::PostgreSql),
        ] {
            for &row in native_account_attribute_bindings(from) {
                if row.column_name == "edge_count" || row.collation_oid != 0 {
                    assert!(!matches_native_account_attribute(to, row));
                }
            }
        }
    }
}
