#!/usr/bin/env python3
"""Exhaustive small-state model for command, authority and outbox durability.

Every mutation uses the same typed authority/lease token path.  Named stale
edges are generated by passing stale tokens into those paths; they are not
predeclared success/failure outcomes.
"""
from __future__ import annotations

import argparse
import json
from collections import deque
from dataclasses import dataclass, replace
from typing import Iterable

ABSENT = "absent"
READY = "ready"
LEASED = "leased"
DELIVERED = "delivered"
DEAD = "dead"
MAX_ATTEMPTS = 2
CLAIM_ACTIONS = ((1, "claim:1"), (2, "claim:2"))


@dataclass(frozen=True, slots=True)
class LeaseToken:
    owner: int
    lease_generation: int
    authority_generation: int


@dataclass(frozen=True, slots=True)
class State:
    authority_generation: int = 1
    revision: int = 0
    command_authority_generation: int | None = None
    receipt_fingerprint: str | None = None
    outbox_state: str = ABSENT
    attempt: int = 0
    lease_generation: int = 0
    lease_owner: int | None = None
    lease_authority_generation: int | None = None
    last_lease_owner: int | None = None
    last_lease_authority_generation: int | None = None
    lease_expired: bool = False
    publish_calls: int = 0
    visible_effect_count: int = 0
    published_authority_generation: int | None = None
    delivered_receipt: bool = False
    delivery_ack_owner: int | None = None
    delivery_ack_generation: int | None = None
    delivery_ack_authority_generation: int | None = None
    terminal_conflicts: int = 0
    stale_rejections: int = 0
    stale_authority_acceptances: int = 0


@dataclass(frozen=True, slots=True)
class Edge:
    action: str
    state: State


def stale_authority_generation(state: State) -> int:
    return max(0, state.authority_generation - 1)


def commit_command(
    state: State,
    *,
    caller_authority_generation: int,
    fingerprint: str,
) -> State:
    """Apply or replay one command only for the exact current authority."""
    if caller_authority_generation != state.authority_generation:
        return replace(state, stale_rejections=state.stale_rejections + 1)
    if state.receipt_fingerprint is None:
        return replace(
            state,
            revision=state.revision + 1,
            command_authority_generation=caller_authority_generation,
            receipt_fingerprint=fingerprint,
            outbox_state=READY,
        )
    if state.receipt_fingerprint == fingerprint:
        return state
    return replace(state, terminal_conflicts=state.terminal_conflicts + 1)


def current_lease_token(state: State) -> LeaseToken:
    if (
        state.outbox_state != LEASED
        or state.lease_owner is None
        or state.lease_authority_generation is None
    ):
        raise ValueError("current lease token requested outside leased state")
    return LeaseToken(
        state.lease_owner,
        state.lease_generation,
        state.lease_authority_generation,
    )


def token_matches_lease(state: State, token: LeaseToken) -> bool:
    return (
        state.outbox_state == LEASED
        and token.owner == state.lease_owner
        and token.lease_generation == state.lease_generation
        and token.authority_generation == state.lease_authority_generation
    )


def claim_edges(state: State) -> Iterable[Edge]:
    if state.attempt >= MAX_ATTEMPTS:
        return
    for owner, action in CLAIM_ACTIONS:
        yield Edge(
            action,
            replace(
                state,
                outbox_state=LEASED,
                attempt=state.attempt + 1,
                lease_generation=state.lease_generation + 1,
                lease_owner=owner,
                lease_authority_generation=state.authority_generation,
                last_lease_owner=owner,
                last_lease_authority_generation=state.authority_generation,
                lease_expired=False,
            ),
        )


def publish_with_token(
    state: State,
    token: LeaseToken,
    *,
    duplicate_visible_effect: bool = False,
    allow_stale_authority_publish: bool = False,
) -> State:
    """Publish only when both lease identity and authority generation are live."""
    exact_lease = token_matches_lease(state, token)
    current_authority = token.authority_generation == state.authority_generation
    if not exact_lease or not current_authority:
        if allow_stale_authority_publish and exact_lease and not current_authority:
            next_count = max(1, state.visible_effect_count)
            return replace(
                state,
                publish_calls=state.publish_calls + 1,
                visible_effect_count=next_count,
                published_authority_generation=(
                    state.published_authority_generation
                    if state.published_authority_generation is not None
                    else token.authority_generation
                ),
                stale_authority_acceptances=state.stale_authority_acceptances + 1,
            )
        return replace(state, stale_rejections=state.stale_rejections + 1)

    next_count = state.visible_effect_count
    published_generation = state.published_authority_generation
    if next_count == 0:
        next_count = 1
        published_generation = token.authority_generation
    elif duplicate_visible_effect:
        next_count += 1
    return replace(
        state,
        publish_calls=state.publish_calls + 1,
        visible_effect_count=next_count,
        published_authority_generation=published_generation,
    )


def acknowledge_with_token(
    state: State,
    token: LeaseToken,
    *,
    allow_stale_ack: bool = False,
    allow_stale_authority_ack: bool = False,
) -> State:
    """Persist completion only for the exact live lease and authority token."""
    exact_lease = token_matches_lease(state, token)
    current_authority = token.authority_generation == state.authority_generation
    has_effect = state.visible_effect_count == 1
    if exact_lease and current_authority and has_effect:
        return replace(
            state,
            outbox_state=DELIVERED,
            lease_owner=None,
            lease_authority_generation=None,
            lease_expired=False,
            delivered_receipt=True,
            delivery_ack_owner=token.owner,
            delivery_ack_generation=token.lease_generation,
            delivery_ack_authority_generation=token.authority_generation,
        )

    if allow_stale_authority_ack and exact_lease and not current_authority and has_effect:
        return replace(
            state,
            outbox_state=DELIVERED,
            lease_owner=None,
            lease_authority_generation=None,
            lease_expired=False,
            delivered_receipt=True,
            delivery_ack_owner=token.owner,
            delivery_ack_generation=token.lease_generation,
            delivery_ack_authority_generation=token.authority_generation,
            stale_authority_acceptances=state.stale_authority_acceptances + 1,
        )

    if allow_stale_ack and has_effect:
        wrong_owner = 2 if state.lease_owner == 1 else 1
        return replace(
            state,
            outbox_state=DELIVERED,
            lease_owner=None,
            lease_authority_generation=None,
            lease_expired=False,
            delivered_receipt=True,
            delivery_ack_owner=wrong_owner,
            delivery_ack_generation=max(0, state.lease_generation - 1),
            delivery_ack_authority_generation=max(
                0, state.authority_generation - 1
            ),
        )

    return replace(state, stale_rejections=state.stale_rejections + 1)


def transition(
    state: State,
    *,
    allow_stale_ack: bool = False,
    duplicate_visible_effect: bool = False,
    allow_stale_authority_publish: bool = False,
    allow_stale_authority_ack: bool = False,
) -> Iterable[Edge]:
    yield Edge(
        "takeover",
        replace(state, authority_generation=state.authority_generation + 1),
    )

    current_generation = state.authority_generation
    stale_generation = stale_authority_generation(state)
    if state.receipt_fingerprint is None:
        yield Edge(
            f"commit:g{current_generation}:A",
            commit_command(
                state,
                caller_authority_generation=current_generation,
                fingerprint="A",
            ),
        )
        yield Edge(
            f"commit:g{stale_generation}:A",
            commit_command(
                state,
                caller_authority_generation=stale_generation,
                fingerprint="A",
            ),
        )
    else:
        yield Edge(
            f"replay:g{current_generation}:A",
            commit_command(
                state,
                caller_authority_generation=current_generation,
                fingerprint="A",
            ),
        )
        yield Edge(
            f"replay:g{current_generation}:B",
            commit_command(
                state,
                caller_authority_generation=current_generation,
                fingerprint="B",
            ),
        )
        yield Edge(
            f"replay:g{stale_generation}:A",
            commit_command(
                state,
                caller_authority_generation=stale_generation,
                fingerprint="A",
            ),
        )

    if state.outbox_state == READY:
        yield from claim_edges(state)

    if state.outbox_state == LEASED:
        token = current_lease_token(state)
        yield Edge(
            "publish_with_exact_lease_token",
            publish_with_token(
                state,
                token,
                duplicate_visible_effect=duplicate_visible_effect,
                allow_stale_authority_publish=allow_stale_authority_publish,
            ),
        )
        wrong_token = LeaseToken(
            2 if token.owner == 1 else 1,
            max(0, token.lease_generation - 1),
            token.authority_generation,
        )
        yield Edge(
            "publish_with_stale_owner_or_generation",
            publish_with_token(state, wrong_token),
        )

        if state.visible_effect_count == 1:
            yield Edge(
                "ack_with_exact_lease_token",
                acknowledge_with_token(
                    state,
                    token,
                    allow_stale_authority_ack=allow_stale_authority_ack,
                ),
            )
            yield Edge(
                "ack_with_stale_owner_or_generation",
                acknowledge_with_token(
                    state,
                    wrong_token,
                    allow_stale_ack=allow_stale_ack,
                ),
            )

        yield Edge("crash_before_or_after_publish", state)

        if not state.lease_expired:
            yield Edge("lease_expire", replace(state, lease_expired=True))
        elif state.attempt < MAX_ATTEMPTS:
            yield from claim_edges(state)
        else:
            yield Edge(
                "reap_expired_at_limit",
                replace(
                    state,
                    outbox_state=DEAD,
                    lease_owner=None,
                    lease_authority_generation=None,
                    lease_expired=False,
                    delivered_receipt=False,
                    delivery_ack_owner=None,
                    delivery_ack_generation=None,
                    delivery_ack_authority_generation=None,
                ),
            )

    if state.outbox_state in (DELIVERED, DEAD):
        yield Edge("terminal_replay", state)


def assert_invariants(state: State) -> None:
    if state.authority_generation < 1:
        raise AssertionError("authority generation must be positive")
    if state.revision not in (0, 1):
        raise AssertionError("revision advanced more than one unique command")
    if (state.receipt_fingerprint is None) != (state.revision == 0):
        raise AssertionError("receipt and revision diverged")
    if state.receipt_fingerprint is None:
        if state.command_authority_generation is not None:
            raise AssertionError("uncommitted command retains authority generation")
    elif (
        state.command_authority_generation is None
        or not 1 <= state.command_authority_generation <= state.authority_generation
    ):
        raise AssertionError("accepted command lacks valid authority generation")

    if state.outbox_state == ABSENT and state.receipt_fingerprint is not None:
        raise AssertionError("accepted command lost its outbox intent")
    if state.outbox_state != ABSENT and state.receipt_fingerprint is None:
        raise AssertionError("outbox exists without accepted command")

    if state.visible_effect_count not in (0, 1):
        raise AssertionError("duplicate externally visible effect")
    if state.publish_calls < state.visible_effect_count:
        raise AssertionError("visible effect lacks publish attempt")
    if state.visible_effect_count == 0:
        if state.published_authority_generation is not None:
            raise AssertionError("absent effect retains publish authority")
    elif (
        state.published_authority_generation is None
        or not 1
        <= state.published_authority_generation
        <= state.authority_generation
    ):
        raise AssertionError("visible effect lacks valid publish authority")

    if state.attempt == 0:
        if (
            state.lease_generation != 0
            or state.last_lease_owner is not None
            or state.last_lease_authority_generation is not None
        ):
            raise AssertionError("unclaimed intent retains lease history")
    elif (
        state.lease_generation == 0
        or state.last_lease_owner not in (1, 2)
        or state.last_lease_authority_generation is None
        or not 1
        <= state.last_lease_authority_generation
        <= state.authority_generation
    ):
        raise AssertionError("claimed intent lacks authority-bound lease history")

    if state.outbox_state == LEASED:
        if (
            state.lease_owner not in (1, 2)
            or state.lease_owner != state.last_lease_owner
            or state.lease_authority_generation
            != state.last_lease_authority_generation
        ):
            raise AssertionError("leased intent lacks exact authority-bound owner")
        if state.attempt == 0 or state.attempt > MAX_ATTEMPTS:
            raise AssertionError("leased intent has invalid attempt")
    elif state.lease_owner is not None or state.lease_authority_generation is not None:
        raise AssertionError("non-leased intent retains current lease token")

    if state.lease_expired and state.outbox_state != LEASED:
        raise AssertionError("only a leased intent may be expired")

    if state.outbox_state == DELIVERED:
        if not state.delivered_receipt:
            raise AssertionError("delivered intent lacks durable receipt")
        if state.visible_effect_count != 1:
            raise AssertionError(
                "delivery receipt exists without exactly one visible effect"
            )
        if (
            state.delivery_ack_owner != state.last_lease_owner
            or state.delivery_ack_generation != state.lease_generation
            or state.delivery_ack_authority_generation
            != state.last_lease_authority_generation
        ):
            raise AssertionError("stale delivery acknowledgement")
    elif (
        state.delivered_receipt
        or state.delivery_ack_owner is not None
        or state.delivery_ack_generation is not None
        or state.delivery_ack_authority_generation is not None
    ):
        raise AssertionError("non-delivered intent retains delivery acknowledgement")

    if state.outbox_state == DEAD and state.delivered_receipt:
        raise AssertionError("dead intent contains delivery receipt")
    if state.stale_authority_acceptances != 0:
        raise AssertionError("stale authority accepted mutation")
    if state.stale_rejections < 0 or state.terminal_conflicts < 0:
        raise AssertionError("negative rejection counter")


def explore(
    depth: int = 10,
    *,
    allow_stale_ack: bool = False,
    duplicate_visible_effect: bool = False,
    allow_stale_authority_publish: bool = False,
    allow_stale_authority_ack: bool = False,
) -> dict[str, int]:
    initial = State()
    queue = deque([(initial, 0)])
    seen = {initial}
    edges = 0
    terminal = 0
    delivered = 0
    dead = 0
    dead_with_visible_effect = 0
    idempotent_retry_states = 0
    stale_authority_rejection_states = 0
    reclaimed_after_takeover_states = 0

    while queue:
        state, level = queue.popleft()
        assert_invariants(state)
        terminal += state.outbox_state in (DELIVERED, DEAD)
        delivered += state.outbox_state == DELIVERED
        dead += state.outbox_state == DEAD
        dead_with_visible_effect += (
            state.outbox_state == DEAD and state.visible_effect_count == 1
        )
        idempotent_retry_states += (
            state.publish_calls > 1 and state.visible_effect_count == 1
        )
        stale_authority_rejection_states += (
            state.authority_generation > 1 and state.stale_rejections > 0
        )
        reclaimed_after_takeover_states += (
            state.outbox_state == LEASED
            and state.command_authority_generation is not None
            and state.lease_authority_generation == state.authority_generation
            and state.lease_authority_generation
            > state.command_authority_generation
        )
        if level == depth:
            continue
        for edge in transition(
            state,
            allow_stale_ack=allow_stale_ack,
            duplicate_visible_effect=duplicate_visible_effect,
            allow_stale_authority_publish=allow_stale_authority_publish,
            allow_stale_authority_ack=allow_stale_authority_ack,
        ):
            edges += 1
            assert_invariants(edge.state)
            if edge.state not in seen:
                seen.add(edge.state)
                queue.append((edge.state, level + 1))

    if delivered == 0 or dead == 0:
        raise AssertionError("terminal delivery and reaper paths must both be reachable")
    if dead_with_visible_effect == 0:
        raise AssertionError("crash-after-publish ambiguity path must be reachable")
    if idempotent_retry_states == 0:
        raise AssertionError("idempotent publish retry path must be reachable")
    if stale_authority_rejection_states == 0:
        raise AssertionError("stale authority rejection path must be reachable")
    if reclaimed_after_takeover_states == 0:
        raise AssertionError("fresh authority reclaim path must be reachable")

    return {
        "depth": depth,
        "states": len(seen),
        "edges": edges,
        "terminal_states_seen": terminal,
        "delivered_states_seen": delivered,
        "dead_states_seen": dead,
        "dead_with_visible_effect_states_seen": dead_with_visible_effect,
        "idempotent_retry_states_seen": idempotent_retry_states,
        "stale_authority_rejection_states_seen": stale_authority_rejection_states,
        "reclaimed_after_takeover_states_seen": reclaimed_after_takeover_states,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--depth", type=int, default=10)
    args = parser.parse_args()
    if not 1 <= args.depth <= 14:
        parser.error("depth must be between 1 and 14")
    report = explore(args.depth)
    print(json.dumps(report, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
